stages:
  - test
  - deploy


test:
  stage: test

  image: blang/latex:ubuntu

  before_script:
    - apt-get update -y
    - apt-get install apt-transport-https -y
    ## SBT sources
    - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823

    - apt-get update -y
    - apt-get install -y default-jre sbt

  script:
    - make testtex
    - make coverage
    # output the coverage report to capture it with a regex and get a badge
    - head -n 2 code/monoid/target/scala-2.12/scoverage-report/scoverage.xml | tail -n 1

  artifacts:
    paths:
      - code/monoid/target/scala-2.12/scoverage-report/
      - slides/part1/part1.pdf
      - slides/part2/part2.pdf

pages:
  stage: deploy

  dependencies:
    - test

  before_script:
    - mkdir public

  script:
    - mv code/monoid/target/scala-2.12/scoverage-report/ public/coverage
    - mv slides/part1/part1.pdf slides/part2/part2.pdf public/

  artifacts:
    paths:
      - public

  only:
    - master
