before_script:
  - uname -a
  - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - apt-get update -y
  - apt-get install sbt -y

test:
  script:
    - cd code/monoid && sbt clean coverage test coverageReport
